# Site settings
title:          PO Network
description:    "Participation officers network in Taiwanese government."
baseurl:        ""
url:            "https://github.com/PDIS/po_network"

# Author
author:
  name:         Chester How
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

languages: ["en", "zh-TW"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  zh-TW: 繁體中文
  en: English

collections:
  blogs:
    output: true
